In [2]:
# 1. Data Preprocessing:
import pandas as pd
df = pd.read_csv('anime.csv')
df

,anime_id,name,genre,type,episodes,rating,members
0,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630
1,5114,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy, Magic, Mili...",TV,64,9.26,793665
2,28977,Gintama°,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.25,114262
3,9253,Steins;Gate,"Sci-Fi, Thriller",TV,24,9.17,673572
4,9969,Gintama&#039;,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.16,151266
...,...,...,...,...,...,...,...
12289,9316,Toushindai My Lover: Minami tai Mecha-Minami,Hentai,OVA,1,4.15,211
12290,5543,Under World,Hentai,OVA,1,4.28,183
12291,5621,Violence Gekiga David no Hoshi,Hentai,OVA,4,4.88,219
12292,6133,Violence Gekiga Shin David no Hoshi: Inma Dens...,Hentai,OVA,1,4.98,175
12293,26081,Yasuji no Pornorama: Yacchimae!!,Hentai,Movie,1,5.46,142

In [3]:
# Handle missing values
df.dropna(inplace=True)

In [4]:
# Impute null values with mode
for col in df.columns:
  df[col].fillna(df[col].mode()[0], inplace=True)
df

C:\Users\Syed Yaseen Ali\AppData\Local\Temp\ipykernel_15388\463104478.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mode()[0], inplace=True)
C:\Users\Syed Yaseen Ali\AppData\Local\Temp\ipykernel_15388\463104478.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mode()[0], inplace=True)

,anime_id,name,genre,type,episodes,rating,members
0,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630
1,5114,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy, Magic, Mili...",TV,64,9.26,793665
2,28977,Gintama°,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.25,114262
3,9253,Steins;Gate,"Sci-Fi, Thriller",TV,24,9.17,673572
4,9969,Gintama&#039;,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.16,151266
...,...,...,...,...,...,...,...
12289,9316,Toushindai My Lover: Minami tai Mecha-Minami,Hentai,OVA,1,4.15,211
12290,5543,Under World,Hentai,OVA,1,4.28,183
12291,5621,Violence Gekiga David no Hoshi,Hentai,OVA,4,4.88,219
12292,6133,Violence Gekiga Shin David no Hoshi: Inma Dens...,Hentai,OVA,1,4.98,175
12293,26081,Yasuji no Pornorama: Yacchimae!!,Hentai,Movie,1,5.46,142

In [5]:
# Explore the dataset
df.head()

,anime_id,name,genre,type,episodes,rating,members
0,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630
1,5114,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy, Magic, Mili...",TV,64,9.26,793665
2,28977,Gintama°,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.25,114262
3,9253,Steins;Gate,"Sci-Fi, Thriller",TV,24,9.17,673572
4,9969,Gintama&#039;,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.16,151266

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 12017 entries, 0 to 12293
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   anime_id  12017 non-null  int64
 1   name      12017 non-null  object
 2   genre     12017 non-null  object
 3   type      12017 non-null  object
 4   episodes  12017 non-null  object
 5   rating    12017 non-null  float64
 6   members   12017 non-null  int64
dtypes: float64(1), int64(2), object(4)
memory usage: 751.1+ KB

In [7]:
df.describe()

           anime_id        rating       members
count  12017.000000  12017.000000  1.201700e+04
mean   13638.001165      6.478264  1.834888e+04
std    11231.076675      1.023857  5.537250e+04
min        1.000000      1.670000  1.200000e+01
25%     3391.000000      5.890000  2.250000e+02
50%     9959.000000      6.570000  1.552000e+03
75%    23729.000000      7.180000  9.588000e+03
max    34519.000000     10.000000  1.013917e+06

In [8]:
# 2. Feature Extraction:
# Convert categorical features to numerical using Label Encoding
X_cate = df[['name','genre','type','episodes']]

from sklearn.preprocessing import LabelEncoder
LE = LabelEncoder()

X_cate['name']=LE.fit_transform(X_cate['name'])
X_cate['genre']=LE.fit_transform(X_cate['genre'])
X_cate['type']=LE.fit_transform(X_cate['type'])
X_cate['episodes']=LE.fit_transform(X_cate['episodes'])

X_cate.head()

C:\Users\Syed Yaseen Ali\AppData\Local\Temp\ipykernel_15388\2261394483.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_cate['name']=LE.fit_transform(X_cate['name'])
C:\Users\Syed Yaseen Ali\AppData\Local\Temp\ipykernel_15388\2261394483.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_cate['genre']=LE.fit_transform(X_cate['genre'])
C:\Users\Syed Yaseen Ali\AppData\Local\Temp\ipykernel_15388\2261394483.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_cate['type']=LE.fit_transform(X_cate['type'])
C:\Users\Syed Yaseen Ali\AppData\Local\Temp\ipykernel_15388\2261394483.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_cate['episodes']=LE.fit_transform(X_cate['episodes'])

    name  genre  type  episodes
0   5277   2660     0         0
1   2773    159     5       147
2   3259    527     5       132
3  10032   3205     5        84
4   3250    527     5       132

In [9]:
#Normalization 
X_cont = df[['anime_id','members','rating']]

from sklearn.preprocessing import MinMaxScaler
MM = MinMaxScaler()
X_cont_MM = MM.fit_transform(X_cont)
X_cont_MM = pd.DataFrame(X_cont_MM)
X_cont_MM.columns = list(X_cont)
X_cont_MM.head()

   anime_id   members    rating
0  0.935164  0.197867  0.924370
1  0.148126  0.782769  0.911164
2  0.839446  0.112683  0.909964
3  0.268034  0.664323  0.900360
4  0.288777  0.149180  0.899160

In [10]:
# 3. Recommendation System:
# Design a function to recommend anime based on cosine similarity
from sklearn.metrics.pairwise import cosine_similarity

def recommend_anime(anime_name, df, top_n=10, similarity_threshold=0.5):
  # Prepare data for cosine similarity
  X_cos = X_cate.values  # Use the encoded categorical features

  # Calculate cosine similarity matrix
  cosine_sim = cosine_similarity(X_cos)

  # Get index of the anime
  anime_index = df[df['name'] == anime_name].index[0]

  # Get similarity scores for the anime
  similarity_scores = list(enumerate(cosine_sim[anime_index]))

  # Sort anime by similarity score
  sorted_anime = sorted(similarity_scores, key=lambda x: x[1], reverse=True)

  # Get recommendations above the similarity threshold
  recommended_anime = []
  for i in range(1, len(sorted_anime)):
    anime_idx, score = sorted_anime[i]
    if score >= similarity_threshold:
      recommended_anime.append(df.iloc[anime_idx]['name'])

  # Limit the number of recommendations to top_n
  return recommended_anime[:top_n]

In [11]:
# Given a target anime, recommend a list of similar anime based on cosine similarity scores
target_anime = "Cross Game" 
recommendations = recommend_anime(target_anime, df, top_n=5)

if recommendations:
  print(f"Anime Recommendations for '{target_anime}':")
  for anime in recommendations:
    print(anime)

Anime Recommendations for 'Cross Game':
Comic Party Specials
Dash! Kappei
Dr. Slump
Choegang Habche: Mix Master
Future Card Buddyfight DDD

In [12]:
# Experiment with different threshold values for similarity scores to adjust the recommendation list size.
target_anime2 = "Kimi no Na wa."

print("Recommendations with similarity threshold 0.6:")
recommendations_06 = recommend_anime(target_anime2, df, top_n=10, similarity_threshold=0.6)
for anime in recommendations_06:
  print(anime)

target_anime3 = "Hajime no Ippo: Rising"

print("\nRecommendations with similarity threshold 0.4:")
recommendations_04 = recommend_anime(target_anime3, df, top_n=10, similarity_threshold=0.4)
for anime in recommendations_04:
  print(anime)

Recommendations with similarity threshold 0.6:
Kankara Sanshin
Kodomo no Keijijougaku
Lily C.A.T.
Kita e.: Diamond Dust Drops Special
Jubilee
Kanashimi no Belladonna
MONSTER GENERATiON
Hikaru no Go Special
Hikaru no Go: New Year Special
Jinkou no Rakuen

Recommendations with similarity threshold 0.4:
Hajime no Ippo: New Challenger
Hello Kitty: Ringo no Mori to Parallel Town
Haikyuu!! Second Season
Kakyuusei
Haikyuu!!
Hanaukyou Maid-tai OVA
Kowaku no Toki
Girls und Panzer: Nihon Senshadou Renmei News
Kono Danshi, Mahou ga Oshigoto Desu.
Gyakuten Saiban: Sono &quot;Shinjitsu&quot;, Igi Ari!

In [13]:
# 4. Evaluation:
# split the data into X and Y variables
X = pd.concat([X_cont_MM, X_cate], axis=1)
print(X.shape)

y = X['type'] 
print(y.shape)

(12284, 7)
(12284,)

In [14]:
#Impute null values with mode
for col in X.columns:
  X[col].fillna(X[col].mode()[0], inplace=True)
X

C:\Users\Syed Yaseen Ali\AppData\Local\Temp\ipykernel_15388\1075386325.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  X[col].fillna(X[col].mode()[0], inplace=True)

       anime_id   members    rating     name   genre  type  episodes
0      0.935164  0.197867  0.924370   5277.0  2660.0   0.0       0.0
1      0.148126  0.782769  0.911164   2773.0   159.0   5.0     147.0
2      0.839446  0.112683  0.909964   3259.0   527.0   5.0     132.0
3      0.268034  0.664323  0.900360  10032.0  3205.0   5.0      84.0
4      0.288777  0.149180  0.899160   3250.0   527.0   5.0     132.0
...         ...       ...       ...      ...     ...   ...       ...
12289  0.000000  0.000047  0.519808  10899.0  2874.0   3.0       0.0
12290  0.000000  0.000047  0.519808  11163.0  2874.0   3.0       0.0
12291  0.000000  0.000047  0.519808  11304.0  2874.0   3.0     118.0
12292  0.000000  0.000047  0.519808  11305.0  2874.0   3.0       0.0
12293  0.000000  0.000047  0.519808  11640.0  2874.0   0.0       0.0

[12284 rows x 7 columns]

In [15]:
# Split the dataset into training and testing sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [16]:
# Model fitting
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()

model.fit(X, y)

y_pred= model.predict(X) 
y_pred= pd.DataFrame(y_pred)
y_pred.value_counts()

C:\Users\Syed Yaseen Ali\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

0
5.0    4623
0.0    4490
3.0    3171
Name: count, dtype: int64

In [17]:
# Evaluate using appropriate metrics such as precision, recall, and F1-score.
from sklearn.metrics import precision_score, recall_score, f1_score

precision = precision_score(y, y_pred, average='micro')
recall = recall_score(y, y_pred, average='micro')
f1 = f1_score(y, y_pred, average='micro')

print("Precision:", precision)
print("Recall:", recall)
print("F1-score:", f1)

Precision: 0.4280364702051449
Recall: 0.4280364702051449
F1-score: 0.4280364702051449

In [65]:
# Analyse the performance of the recommendation system and identify areas of improvement.

# - Calculate metrics like precision, recall and f1 using a held-out test set.
# - Implement strategies to handle new users or anime with little to no interaction data.
# - Explore more sophisticated feature engineering techniques to capture richer information about anime and user preferences.
# - Experiment with different recommendation algorithms to find the best fit for the dataset and user needs.
# - Optimize hyperparameters of the chosen algorithm to improve performance.